# Project: test
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o acllib.o
LINKOBJ  = main.o acllib.o
LIBS     = -L"F:/Dev-Cpp/MinGW32/lib" -L"F:/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc -mwindows F:/Dev-Cpp/MinGW32/lib/libwinmm.a F:/Dev-Cpp/MinGW32/lib/libuuid.a F:/Dev-Cpp/MinGW32/lib/liboleaut32.a F:/Dev-Cpp/MinGW32/lib/libole32.a F:/Dev-Cpp/MinGW32/lib/libgdi32.a F:/Dev-Cpp/MinGW32/lib/libuser32.a F:/Dev-Cpp/MinGW32/lib/libkernel32.a F:/Dev-Cpp/MinGW32/lib/libmsimg32.a -g3
INCS     = -I"F:/Dev-Cpp/MinGW32/include" -I"F:/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"F:/Dev-Cpp/MinGW32/include" -I"F:/Dev-Cpp/MinGW32/include"
BIN      = test.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

acllib.o: acllib.c
	$(CC) -c acllib.c -o acllib.o $(CFLAGS)
